CREATE TABLE `approval_template` (
  `id` varchar(191) NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL,
  `is_deleted` int NOT NULL DEFAULT 0,
  `name` varchar(191) NOT NULL,
  `type` varchar(191) NOT NULL,
  `platform_name` varchar(191) NOT NULL,
  `department_name` varchar(191) NOT NULL,
  `status` varchar(191) NOT NULL,
  `description` text NULL,
  `updated_at` varchar(191) NOT NULL,
  `nodes` json NOT NULL,
  INDEX `approval_template_status_update_time_idx`(`status`, `update_time`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `approval_request` (
  `id` varchar(191) NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL,
  `is_deleted` int NOT NULL DEFAULT 0,
  `request_no` varchar(191) NOT NULL,
  `template_id` varchar(191) NOT NULL,
  `template_name` varchar(191) NOT NULL,
  `type` varchar(191) NOT NULL,
  `applicant_id` varchar(191) NOT NULL,
  `applicant_name` varchar(191) NOT NULL,
  `current_approver_id` varchar(191) NULL,
  `current_approver_name` varchar(191) NULL,
  `status` varchar(191) NOT NULL,
  `amount` decimal(10, 2) NULL,
  `platform_name` varchar(191) NOT NULL,
  `department_name` varchar(191) NOT NULL,
  `summary` text NOT NULL,
  `created_at` varchar(191) NOT NULL,
  `updated_at` varchar(191) NOT NULL,
  `progress` json NOT NULL,
  UNIQUE INDEX `approval_request_request_no_key`(`request_no`),
  INDEX `approval_request_status_update_time_idx`(`status`, `update_time`),
  INDEX `approval_request_applicant_id_update_time_idx`(`applicant_id`, `update_time`),
  INDEX `approval_request_current_approver_id_update_time_idx`(`current_approver_id`, `update_time`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
