// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/system/users","parentId":"2","id":"3"},"4":{"path":"/system/users","parentId":"2","id":"4"},"5":{"path":"/system/roles","parentId":"2","id":"5"},"6":{"path":"/system/menus","parentId":"2","id":"6"},"7":{"path":"/system/buttons","parentId":"2","id":"7"},"8":{"path":"/system/apis","parentId":"2","id":"8"},"9":{"path":"/system/platforms","parentId":"2","id":"9"},"10":{"path":"/system/departments","parentId":"2","id":"10"},"11":{"path":"/system/shops","parentId":"2","id":"11"},"12":{"path":"/system/logs","parentId":"2","id":"12"},"13":{"path":"/org/departments","parentId":"2","id":"13"},"14":{"path":"/org/positions","parentId":"2","id":"14"},"15":{"path":"/org/employees","parentId":"2","id":"15"},"16":{"path":"/attendance/schedules","parentId":"2","id":"16"},"17":{"path":"/attendance/requests","parentId":"2","id":"17"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout" */'@/layouts/BasicLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__system__users__index" */'@/pages/system/users/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__system__roles__index" */'@/pages/system/roles/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__system__menus__index" */'@/pages/system/menus/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__system__buttons__index" */'@/pages/system/buttons/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__system__apis__index" */'@/pages/system/apis/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__system__platforms__index" */'@/pages/system/platforms/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__system__departments__index" */'@/pages/system/departments/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__system__shops__index" */'@/pages/system/shops/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__system__logs__index" */'@/pages/system/logs/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__personnel__departments__index" */'@/pages/personnel/departments/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__personnel__positions__index" */'@/pages/personnel/positions/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__personnel__employees__index" */'@/pages/personnel/employees/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__attendance__schedules__index" */'@/pages/attendance/schedules/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__attendance__requests__index" */'@/pages/attendance/requests/index.tsx')),
},
  };
}
