CREATE TABLE `approval_event` (
  `id` varchar(191) NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL,
  `is_deleted` int NOT NULL DEFAULT 0,
  `request_id` varchar(191) NOT NULL,
  `request_no` varchar(191) NOT NULL,
  `biz_type` varchar(191) NULL,
  `biz_id` varchar(191) NULL,
  `event_type` varchar(191) NOT NULL,
  `event_source` varchar(191) NOT NULL,
  `request_status_from` varchar(191) NULL,
  `request_status_to` varchar(191) NULL,
  `biz_status_from` int NULL,
  `biz_status_to` int NULL,
  `operator_id` varchar(191) NULL,
  `operator_name` varchar(191) NULL,
  `dedup_key` varchar(191) NULL,
  `external_event_id` varchar(191) NULL,
  `payload` json NULL,
  UNIQUE INDEX `approval_event_dedup_key_key`(`dedup_key`),
  INDEX `approval_event_request_id_create_time_idx`(`request_id`, `create_time`),
  INDEX `approval_event_request_no_create_time_idx`(`request_no`, `create_time`),
  INDEX `approval_event_event_type_create_time_idx`(`event_type`, `create_time`),
  INDEX `approval_event_event_source_create_time_idx`(`event_source`, `create_time`),
  INDEX `approval_event_biz_type_biz_id_create_time_idx`(`biz_type`, `biz_id`, `create_time`),
  INDEX `approval_event_external_event_id_idx`(`external_event_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
