-- CreateTable
CREATE TABLE `sys_file` (
    `id` VARCHAR(191) NOT NULL,
    `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `update_time` DATETIME(3) NOT NULL,
    `is_deleted` INTEGER NOT NULL DEFAULT 0,
    `original_name` VARCHAR(255) NOT NULL,
    `stored_name` VARCHAR(500) NOT NULL,
    `file_size` BIGINT NOT NULL,
    `mime_type` VARCHAR(100) NOT NULL,
    `extension` VARCHAR(20) NOT NULL,
    `platform_id` VARCHAR(50) NOT NULL,
    `department_id` VARCHAR(50) NULL,
    `category` VARCHAR(50) NOT NULL,
    `entity_type` VARCHAR(50) NULL,
    `entity_id` VARCHAR(50) NULL,
    `storage_type` VARCHAR(20) NOT NULL,
    `bucket_name` VARCHAR(100) NULL,
    `is_public` INTEGER NOT NULL DEFAULT 0,
    `access_count` INTEGER NOT NULL DEFAULT 0,
    `status` VARCHAR(20) NOT NULL DEFAULT 'active',
    `metadata` JSON NULL,
    `uploaded_by` VARCHAR(50) NOT NULL,
    `uploaded_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `deleted_at` DATETIME(3) NULL,
    `deleted_by` VARCHAR(50) NULL,

    INDEX `sys_file_platform_id_department_id_idx`(`platform_id`, `department_id`),
    INDEX `sys_file_category_entity_type_entity_id_idx`(`category`, `entity_type`, `entity_id`),
    INDEX `sys_file_uploaded_by_idx`(`uploaded_by`),
    INDEX `sys_file_status_idx`(`status`),
    INDEX `sys_file_create_time_idx`(`create_time`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
